GorevYoneticisi/GorevYoneticisi/Controllers/TableByMonthController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using BusinessLayer.Concrete;
using DataAccessLayer.Concrete;
using DataAccessLayer.Concrete.EntityFramework;
using EntityLayer.Concrete;
using Microsoft.AspNetCore.Mvc;

namespace GorevYoneticisi.Controllers
{
    public class TableByMonthController : Controller
    {
        PlanManager pm = new PlanManager(new EfPlanRepository());
        public IActionResult Index()
        {
           
            return View();
        }
        public IActionResult MonthList(DateTime datee)
        {
            DateTime tt = datee;
            TimeSpan ts = datee.AddMonths(1) - tt;
            var day = datee.Date;
            ViewBag.MonthName = datee.ToString("MMM");
            var ua = User.Identity.Name;
            Context c = new Context();
            var ub = c.Userdb.Where(x => x.UserName == ua).Select(y => y.UserID).FirstOrDefault();
            var plans = pm.GetListWithUserIDByPlan(ub);
            List<Plan> vPlans = new List<Plan>();
            for (int i = 0; i < ts.Days; i++)
            {
                foreach (var item in plans) { if (item.PlanDay.Date == day) { vPlans.Add(item); } }

                day = day.AddDays(1);
            }
            return View("MonthList", vPlans);
        }

       
    }
}

GorevYoneticisi/GorevYoneticisi/Views/TableByMonth/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/UserLayout.cshtml";
}

<div class="main-panel">
    <div class="content-wrapper">
        <div class="row">
            <div class="col-12 grid-margin stretch-card">
                <div class="card">
                    <div class="card-body">
                        @using (Html.BeginForm("MonthList", "TableByMonth", FormMethod.Post))
                        {
                            <h4 class="card-title"></h4>
                               
                                
                            <div class="form-group">
                                <label>Tarih Belirle</label>
                                <input class="form-group" type="month" name="datee"/>

                            </div>
                            <button type="submit" class="btn btn-gradient-danger mr-2">Listele</button>
                        }
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>

GorevYoneticisi/GorevYoneticisi/Views/TableByMonth/MonthList.cshtml
@using EntityLayer.Concrete
@model List<Plan>
@{
    ViewData["Title"] = "MonthList";
    Layout = "~/Views/Shared/UserLayout.cshtml";
}

<div class="container-scroller">
    <div class="main-panel">
        <div class="content-wrapper">
            <div class="row">
                <div class="col-12 grid-margin stretch-card">
                    <div class="card">
                        <div class="card-body">
                            @using (Html.BeginForm("MonthList", "TableByMonth", FormMethod.Post))
                            {
                                <h4 class="card-title">Plan tarihi seç</h4>
                               
                                
                                <div class="form-group">
                                    <label>Tarih Belirle</label>
                                    <input class="form-group" type="month" name="datee"/>

                                </div>
                                <button type="submit" class="btn btn-gradient-danger mr-2">Göster</button>
                            }
                        </div>
                        
                        <div class="card-body">
                            <h4 class="card-title">@ViewBag.MonthName Ayı Plan Listesi</h4>
     
                            <table class="table table-dark">
                                <thead>
                                <tr>
                                    <th> Plan Saati </th>
                                    <th> Plan Başlığı </th>
                                    <th> Plan Detayı </th>
                            
                                </thead>
                                <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>@item.PlanDay.ToString("f") </td>
                                        <td> @item.PlanTitle </td>
                                        <td> @item.PlanContent </td>
                                 
                    

                                    </tr>
                                }
                                </tbody>
                            </table>
                        </div>
                        

                    </div>

                </div>
            </div>
        </div>
    </div>
</div>