GorevYoneticisi/GorevYoneticisi/Controllers/TableByDayController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using BusinessLayer.Concrete;
using DataAccessLayer.Concrete;
using DataAccessLayer.Concrete.EntityFramework;
using EntityLayer.Concrete;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace GorevYoneticisi.Controllers
{
    
    public class TableByDayController : Controller
    {

        PlanManager pm = new PlanManager(new EfPlanRepository());
        public IActionResult Index()
        {
            return View();
        }
      
        public IActionResult ToDoList(DateTime datee)
        {
            var day = datee.Date;
            ViewBag.dayName = datee.ToString("D");
            var ua = User.Identity.Name;
            Context c = new Context();
            var ub = c.Userdb.Where(x => x.UserName == ua).Select(y => y.UserID).FirstOrDefault();
            var plans = pm.GetListWithUserIDByPlan(ub);
            List<Plan> vPlans = new List<Plan>();
            foreach (var item in plans) { if (item.PlanDay.Date==day) { vPlans.Add(item); } }

            return View("ToDoList",vPlans);
        }

        public IActionResult DeletePlan(int id)
        {

            var planvalue = pm.TGetById(id);
            pm.TDelete(planvalue);
            var day = planvalue.PlanDay.Date;
            ViewBag.dayName = planvalue.PlanDay.ToString("D");
            var ua = User.Identity.Name;
            Context c = new Context();
            var ub = c.Userdb.Where(x => x.UserName == ua).Select(y => y.UserID).FirstOrDefault();
            var plans = pm.GetListWithUserIDByPlan(ub);
            List<Plan> vPlans = new List<Plan>();
            foreach (var item in plans) { if (item.PlanDay.Date == day) { vPlans.Add(item); } }

            return View("ToDoList",vPlans);
        }
        [HttpGet]
        public IActionResult EditPlan(int id)
        {
            var planvalue=pm.TGetById(id);
            var day = planvalue.PlanDay.Date;
            ViewBag.dayName = planvalue.PlanDay.ToString("D");
            ViewBag.dayTime = planvalue.PlanDay.ToString("t");
            return View(planvalue);
        }
        [HttpPost]
        public IActionResult EditPlan(Plan p)
        {
            var planvalue = pm.TGetById(p.PlanID);
            p.PlanStatus=planvalue.PlanStatus;
            p.PlanCreateDate=planvalue.PlanCreateDate;
            p.PlanID=planvalue.PlanID;
            p.UserID = planvalue.UserID; 
            pm.TUpdate(p);
          
            var day = planvalue.PlanDay.Date;
            ViewBag.dayName = planvalue.PlanDay.ToString("D");
            var plans = pm.GetListWithUserIDByPlan(planvalue.UserID);
            List<Plan> vPlans = new List<Plan>();
            foreach (var item in plans) { if (item.PlanDay.Date == day) { vPlans.Add(item); } }

            return View("ToDoList", vPlans);
        }

    }
}

GorevYoneticisi/GorevYoneticisi/Views/TableByDay/EditPlan.cshtml
@using System.Security.Cryptography.X509Certificates
@model EntityLayer.Concrete.Plan
@{
    ViewData["Title"] = "EditPlan";
    Layout = "~/Views/Shared/UserLayout.cshtml";
}

<div class="col-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            @using (Html.BeginForm("EditPlan", "TableByDay", FormMethod.Post))
            {

                <h4>@ViewBag.dayName günü Saat:@ViewBag.dayTime İçin Planı Düzenle</h4>

                <br />

                <div class="form-group">
                    <div class="form-group">
                        <label for="exampleInputName1">Plan ID</label>
                        @Html.TextBoxFor(x => x.PlanID, new {@class = "form-control",})
                    </div>
                    <div class="form-group">
                        <label for="exampleInputName1">Kullanıcı ID</label>
                        @Html.TextBoxFor(x => x.UserID, new {@class = "form-control",})
                    </div>

                    <label for="exampleInputName1">Yeni Tarih ve Saat Belirle</label>
                    @Html.TextBoxFor(x => x.PlanDay, new {@class = "form-control", @type = "datetime-local"})


                    <div class="form-group">
                        <label for="exampleInputName1">Plan Başlığı</label>
                        @Html.TextBoxFor(x => x.PlanTitle, new {@class = "form-control"})
                    </div>
                    <div class="form-group">
                        <label for="exampleInputName1">Plan İçeriği</label>
                        @Html.TextBoxFor(x => x.PlanContent, new {@class = "form-control"})
                    </div>
                </div>
           
                <button type="submit" class="btn btn-gradient-primary mr-2">Değiştir Ve Kaydet</button>
                <button class="btn btn-light">Cancel</button>
            }
        </div>
    </div>
</div>

GorevYoneticisi/GorevYoneticisi/Views/TableByDay/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/UserLayout.cshtml";
}

<div class="container-scroller">
    <div class="main-panel">
        <div class="content-wrapper">
            <div class="row">
                <div class="col-12 grid-margin stretch-card">
                    <div class="card">
                        <div class="card-body">
                            @using (Html.BeginForm("ToDoList", "TableByDay", FormMethod.Post))
                            {
                                <h4 class="card-title">Plan tarihi seç</h4>
                               
                                
                                <div class="form-group">
                                    <label>Tarih Belirle</label>
                                    <input class="form-group" type="date" name="datee"/>

                                </div>
                                <button type="submit" class="btn btn-gradient-danger mr-2">Göster</button>
                            }
                        </div>
                        
                        

                    </div>

                </div>
            </div>
        </div>
    </div>
</div>

GorevYoneticisi/GorevYoneticisi/Views/TableByDay/ToDoList.cshtml
@using EntityLayer.Concrete
@model List<Plan>
@{
    ViewData["Title"] = "ToDoList";
    Layout = "~/Views/Shared/UserLayout.cshtml";
    
}
<div class="card">
    <div class="card-body">
        @using (Html.BeginForm("ToDoList", "TableByDay", FormMethod.Post))
        {
            <h4 class="card-title">Plan tarihi seç</h4>
                               
                                
            <div class="form-group">
                <label>Tarih Belirle</label>
                <input class="form-group" type="date" name="datee"/>

            </div>
            <button type="submit" class="btn btn-gradient-danger mr-2">Göster</button>
        }
    </div>
    <div class="card-body">
        <h4 class="card-title">@ViewBag.dayName Günü Plan Listesi</h4>
     
        <table class="table table-dark">
            <thead>
            <tr>
                <th> Plan Saati </th>
                <th> Plan Başlığı </th>
                <th> Plan Detayı </th>
                <th> Düzenle </th>
                <th> Sil </th>
            </tr>
            </thead>
            <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.PlanDay.TimeOfDay </td>
                    <td> @item.PlanTitle </td>
                    <td> @item.PlanContent </td>
                    <td> <a href="/TableByDay/EditPlan/@item.PlanID" class="btn btn-outline-warning btn-fw">Düzenle</a> </td>
                    <td> <a href="/TableByDay/DeletePlan/@item.PlanID" class="btn btn-outline-danger btn-fw">Sil</a> </td>
                    

                </tr>
            }
            </tbody>
        </table>
    </div>
</div>